// =============================================================================
// HAMI Widget — Root Component
// =============================================================================
//
// Self-contained. Portals to document.body so the widget floats above
// ALL host-page content, regardless of stacking contexts or z-index.
//
// Launch experience (Version 1):
//   - First visit: auto-opens after 2.5s, shows predefined welcome message,
//     auto-focuses input. sessionStorage prevents repeat on return visits.
//   - Close: minimises to launcher. After 2.5 minutes of inactivity a single
//     subtle reminder tooltip appears once per session.
//
// Usage in any React app:
//   import HAMIWidget from './widget/HAMIWidget.jsx';
//   import './widget/widget.css';
//   <HAMIWidget />
//
// Usage with custom config:
//   import WIDGET_CONFIG from './widget/widget.config.js';
//   const myConfig = { ...WIDGET_CONFIG, ... };
//   <HAMIWidget config={myConfig} />
//
// =============================================================================

import React, { useState, useCallback, useEffect, useRef } from 'react';
import { createPortal } from 'react-dom';

import WidgetLauncher    from './WidgetLauncher.jsx';
import WidgetPanel       from './WidgetPanel.jsx';
import { useWidgetChat } from './useWidgetChat.js';
import DEFAULT_CONFIG    from './widget.config.js';

// ─── Session storage keys ─────────────────────────────────────────────────────
// One key per behaviour. Both are scoped to the browser session (cleared on tab close).

const SK_WELCOME  = 'hami_welcome_shown';   // Set after auto-open fires
const SK_REMINDER = 'hami_reminder_shown';  // Set after reminder is displayed

// ─── Welcome message ─────────────────────────────────────────────────────────
// Predefined — NOT generated by AI. Exact text as specified.

const WELCOME_TEXT = [
  'Welcome to NVeston!',
  "I'm HAMI, NVeston's Strategic Advisory Assistant.",
  "I'm here to answer your questions, explain our services, and help you explore investment and capital allocation decisions with confidence.",
  'How can I help you today?',
].join('\n');

// ─── Timing constants ─────────────────────────────────────────────────────────

const AUTO_OPEN_DELAY_MS  = 2500;          // 2.5 s after page load
const WELCOME_FOCUS_DELAY = 120;           // ms after open before focusing input
const REMINDER_DELAY_MS   = 2.5 * 60_000; // 2.5 min after close
const REMINDER_AUTO_HIDE  = 12_000;        // Reminder auto-hides after 12 s

// =============================================================================

/**
 * @param {{ config?: typeof DEFAULT_CONFIG }} props
 */
export default function HAMIWidget({ config = DEFAULT_CONFIG }) {
  const [isOpen,          setIsOpen]          = useState(false);
  const [focusSignal,     setFocusSignal]     = useState(0);
  const [reminderVisible, setReminderVisible] = useState(false);

  const chat = useWidgetChat({ config });

  const reminderTimerRef  = useRef(null);
  const reminderHideRef   = useRef(null);

  // ── Clear reminder timer (helper) ─────────────────────────────────────────

  const clearReminderTimer = useCallback(() => {
    if (reminderTimerRef.current) {
      clearTimeout(reminderTimerRef.current);
      reminderTimerRef.current = null;
    }
    if (reminderHideRef.current) {
      clearTimeout(reminderHideRef.current);
      reminderHideRef.current = null;
    }
  }, []);

  // ── Open ──────────────────────────────────────────────────────────────────

  const open = useCallback(() => {
    setIsOpen(true);
    setReminderVisible(false);
    clearReminderTimer();
  }, [clearReminderTimer]);

  // ── Close — starts reminder countdown ────────────────────────────────────

  const close = useCallback(() => {
    setIsOpen(false);

    // Only schedule if this session hasn't shown the reminder yet
    if (!sessionStorage.getItem(SK_REMINDER)) {
      clearReminderTimer();

      reminderTimerRef.current = setTimeout(() => {
        // Double-check (visitor may have reopened during the wait)
        if (!sessionStorage.getItem(SK_REMINDER)) {
          sessionStorage.setItem(SK_REMINDER, '1');
          setReminderVisible(true);

          // Auto-hide the reminder after 12 s
          reminderHideRef.current = setTimeout(() => {
            setReminderVisible(false);
          }, REMINDER_AUTO_HIDE);
        }
      }, REMINDER_DELAY_MS);
    }
  }, [clearReminderTimer]);

  // ── Toggle ────────────────────────────────────────────────────────────────

  const toggle = useCallback(() => {
    if (isOpen) close(); else open();
  }, [isOpen, open, close]);

  // ── Escape key ────────────────────────────────────────────────────────────

  const handleKeyDown = useCallback((e) => {
    if (e.key === 'Escape' && isOpen) {
      e.stopPropagation();
      close();
    }
  }, [isOpen, close]);

  // ── First-visit auto-open ─────────────────────────────────────────────────
  // Runs once on mount. Skipped if the visitor has already seen the welcome
  // this session (page refresh also clears sessionStorage, resetting the flow).

  useEffect(() => {
    if (sessionStorage.getItem(SK_WELCOME)) return; // return visitor — stay closed

    const autoOpenTimer = setTimeout(() => {
      sessionStorage.setItem(SK_WELCOME, '1');

      // Open the panel
      setIsOpen(true);

      // Inject the predefined welcome message (not AI-generated)
      chat.injectWelcome(WELCOME_TEXT);

      // Focus the input shortly after the panel finishes rendering
      setTimeout(() => setFocusSignal(s => s + 1), WELCOME_FOCUS_DELAY);
    }, AUTO_OPEN_DELAY_MS);

    return () => clearTimeout(autoOpenTimer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []); // intentionally empty — must run exactly once on mount

  // ── Cleanup on unmount ────────────────────────────────────────────────────

  useEffect(() => () => clearReminderTimer(), [clearReminderTimer]);

  // ─────────────────────────────────────────────────────────────────────────

  return createPortal(
    <div
      className="hami-widget"
      onKeyDown={handleKeyDown}
      data-hami-widget="true"
    >
      {/* Floating launcher — always visible */}
      <WidgetLauncher
        isOpen={isOpen}
        onToggle={toggle}
        reminderText={reminderVisible
          ? "Still have questions? I'm here whenever you're ready."
          : null
        }
        onReminderDismiss={() => {
          setReminderVisible(false);
          clearReminderTimer();
        }}
        config={config}
      />

      {/* Chat panel — rendered only when open */}
      {isOpen && (
        <WidgetPanel
          chat={chat}
          onClose={close}
          focusSignal={focusSignal}
          config={config}
        />
      )}
    </div>,
    document.body
  );
}
